### ISSUE TITLE
Do you know anything about this?

### ISSUE THREAD

**Issue by long1eu** [cedx/setup-dart#1]
![Screenshot 2020-05-15 at 17 26 50](https://user-images.githubusercontent.com/9283414/82061399-5533a280-96d1-11ea-8270-6e784fbde6a9.png)

**Comment by cedx** [comment]
Probably a temporary failure of GitHub.
See this project: https://github.com/cedx/lcov.dart/actions

I've triggered a build two hours ago: everything was OK.
I've just triggered the same build 5 minutes ago: same error as you.

**Comment by cedx** [comment]
@long1eu I've pushed again the `v1` tag, and it seems to have fixed the problem.
Weird...

**Comment by long1eu** [comment]
Thanks
