### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by enyo** [cedx/setup-dart#4]
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

![image](https://user-images.githubusercontent.com/133277/96886891-50df9280-1484-11eb-8aaa-a5c71ede27a1.png)

**Comment by cedx** [comment]
I've released a new version of this action (2.3.0) that upgrades the `@actions/core` package to version 1.2.6.
Can you test if it fixes this issue?

**Comment by enyo** [comment]
Thanks! That did it.
