### ISSUE TITLE
[Feature request] Define a problem matcher for dartanalyzer

### ISSUE THREAD

**Issue by stof** [cedx/setup-dart#8]
It would be great if this action could provide a [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) turning the dartanalyzer output into annotations.

Note that I'm aware that https://github.com/marketplace/actions/dartanalyzer-annotations exists but this one relies on the Checks API to add annotation instead of relying on the github action commands or a problem matcher. This makes it require a github token with write access while PRs opened from a fork have a read-only token.

**Comment by cedx** [comment]
Unfortunately, this is out of scope: the purpose of this action is to install the Dart SDK and nothing else.
Linting the code with `dartanalyzer` should clearly be a new dedicated action.
So, I don't plan to implement this feature... but I'm open to pull requests if you want to try implement it yourself 😄.

**Comment by stof** [comment]
I'm not asking to run the analyzer, but to install a problem matcher at the same time than the sdk. This would be similar to the fact that the setup-node action installs a problem matcher for the eslint output, so that a step running `eslint` gets problem recognized.

**Comment by cedx** [comment]
OK, I'll take a look at it whenever I have some free time.

**Comment by cedx** [comment]
@stof I've been contacted by a member of the Dart team to inform me that an official action was created by them.
See: https://github.com/dart-lang/setup-dart

You should consider:
- using their action instead of mine
- opening the same issue on their repository as I don't plan to maintain this project anymore
